//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnEnglish.Localize {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BankCard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BankCard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LearnEnglish.Localize.BankCard", typeof(BankCard).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add 50 cards.
        /// </summary>
        public static string Add_50_cards {
            get {
                return ResourceManager.GetString("Add_50_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add card.
        /// </summary>
        public static string Add_Сard {
            get {
                return ResourceManager.GetString("Add_Сard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank card.
        /// </summary>
        public static string Bank_Card {
            get {
                return ResourceManager.GetString("Bank_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;root&gt;
        ///  &lt;!-- 
        ///    Microsoft ResX Schema 
        ///    
        ///    Version 2.0
        ///    
        ///    The primary goals of this format is to allow a simple XML format 
        ///    that is mostly human readable. The generation and parsing of the 
        ///    various data types are done through the TypeConverter classes 
        ///    associated with the data types.
        ///    
        ///    Example:
        ///    
        ///    ... ado.net/XML headers &amp; schema ...
        ///    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
        ///    &lt;resheader n [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BankCard_Ru {
            get {
                return ResourceManager.GetString("BankCard_Ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete card.
        /// </summary>
        public static string Delete_Сard {
            get {
                return ResourceManager.GetString("Delete_Сard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id card.
        /// </summary>
        public static string Id_Card {
            get {
                return ResourceManager.GetString("Id_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id owner.
        /// </summary>
        public static string Id_Owner {
            get {
                return ResourceManager.GetString("Id_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about bank cards.
        /// </summary>
        public static string Info_Bank_Card {
            get {
                return ResourceManager.GetString("Info_Bank_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about bank card:.
        /// </summary>
        public static string Info_Bank_Card_One {
            get {
                return ResourceManager.GetString("Info_Bank_Card_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card number.
        /// </summary>
        public static string Number_Of_Card {
            get {
                return ResourceManager.GetString("Number_Of_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of.
        /// </summary>
        public static string Out_of {
            get {
                return ResourceManager.GetString("Out_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions from.
        /// </summary>
        public static string Positions_from {
            get {
                return ResourceManager.GetString("Positions_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove card.
        /// </summary>
        public static string Remove_Сard {
            get {
                return ResourceManager.GetString("Remove_Сard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file .doc.
        /// </summary>
        public static string Save_file_doc {
            get {
                return ResourceManager.GetString("Save_file_doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See all.
        /// </summary>
        public static string See_All {
            get {
                return ResourceManager.GetString("See_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity month.
        /// </summary>
        public static string Validity_Month {
            get {
                return ResourceManager.GetString("Validity_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity (month/year).
        /// </summary>
        public static string Validity_Month_Year {
            get {
                return ResourceManager.GetString("Validity_Month_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity year.
        /// </summary>
        public static string Validity_Year {
            get {
                return ResourceManager.GetString("Validity_Year", resourceCulture);
            }
        }
    }
}
